# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: Cambak

before:
  hooks:
    - go mod tidy
    #- go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - windows # XXX: Not tested for Windows... yet.
      - darwin
      - freebsd
      - openbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64

archives:
  - replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

nfpms:
  - package_name: cambak
    vendor: Themimitoof
    homepage: https://github.com/themimitoof/cambak
    maintainer: Michael V. <dev@mvieira.fr>
    license: MIT
    formats:
      - apk
      - deb
      - rpm

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
